#include "common.h"
#include "page.h"
#include "memory_physical.h"
#include "memory_declaration.h"

#include "memory_util.c"
#include "memory_physical.c"
#include "frame.c"
#include "kheap.c"
#include "page.c"
